package com.orhon.smartcampus.modules.core.graphql.gql.model;

import java.util.Date;

import lombok.Data;

@Data
public class GQLTeacher {;
	    private Long id;
	    private GQLUser user;
	    private String idcard;
	    private GQLDictionary gender;
	    private String birthday;
//	    "籍贯-省";
	    private GQLRegion native_province;
//	    "籍贯-市";
	    private GQLRegion native_city;
//	    "籍贯-县";
	    private GQLRegion native_county;
//	    "出生-省";
	    private GQLRegion birth_province;
//	    "出生-市";
	    private GQLRegion birth_city;
//	    "出生-县";
	    private GQLRegion birth_county;
//	    "人才类型";
	    private GQLDictionary type;
//	    "单位名称（学校ID）";
	    private GQLSchool unit_name;
	    private String email;
	    private String telnumber;
//	    "国际";
	    private GQLDictionary nationality;
//	    "政治面貌";
	    private GQLDictionary political_type;
//	    "在岗状态";
	    private GQLDictionary work_status;
//	    "参加工作时间";
	    private String work_date;
//	    "最高职称";
	    private GQLDictionary job_title;
//	    "最高学历";
	    private GQLDictionary education;
//	    "最高学位";
	    private GQLDictionary degree;
//	    "是否硕导";
	    private GQLDictionary master_supervisor;
//	    "是否博导";
	    private GQLDictionary teach;
//	    "人才类别(按六支队伍分)";
	    private GQLDictionary talent_category_six;
//	    "人才类别(按九支队伍分)";
	    private GQLDictionary talent_category_nine;
//	    "现住址-省";
	    private GQLRegion cmbprovince3;
//	    "现住址-市";
	    private GQLRegion cmbcity3;
//	    "现住址-县";
	    private GQLRegion cmbcounty3;
//	    "户籍所在地-省";
	    private GQLRegion cmbprovince2;
//	    "户籍所在地-市";
	    private GQLRegion cmbcity2;
//	    "户籍所在地-县";
	    private GQLRegion cmbcounty2;
	    private GQLSchool school;
//	    "民族";
	    private GQLDictionary nation;
//	    "公安身份证备案照片";
	    private String imgphotos;
//	    "本人签字图片";
	    private String signimg;
//	    "教师姓名";
	    private GQLLang name;
//	    "简介";
	    private GQLLang introduction;
	    private GQLUser created_by;
	    private GQLUser updated_by;
	    private Date created_at;
	    private Date updated_at;
	    private Date deleted_at;
}
